version: "3.9"

services:
  products-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=ep-proud-dew-agof5ldc-pooler.c-2.eu-central-1.aws.neon.tech;Database=ProductsDb;Username=neondb_owner;Password=npg_Xms7IrJFYp8j;SSLMode=VerifyFull;ChannelBinding=Require
    ports:
      - "8080:8080"
