version: "3.9"
services:
  products-api:
    image: ghcr.io/pedrobelfort/product-cloud/products-api:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=ep-proud-dew-agof5ldc-pooler.c-2.eu-central-1.aws.neon.tech;Database=ProductsDb;Username=neondb_owner;Password=npg_Xms7IrJFYp8j;SSLMode=VerifyFull;ChannelBinding=Require
    ports:
      - "8080:80"  # ‚Üê Azure mapeia 80/443 externamente
